// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  Drupal.behaviors.ScribeAnnotator = {
    attach: function(context, settings) {
      var annotator, opts, perm_opts, plugin, plugins, _results;
      perm_opts = {
        user: Drupal.settings.scribe.username,
        showViewPermissionsCheckbox: false,
        showEditPermissionsCheckbox: false,
        userAuthorize: function(op, annotation, user) {
          return annotation.permissions[op];
        }
      };
      Drupal.annotator = {};
      Drupal.annotator.text = $(context).find('.scribe-text-annotation .field-items').annotator();
      annotator = Drupal.annotator.text;
      plugins = {
        EnhancedPosition: {},
        Threading: {},
        DrupalStore: {},
        DrupalPermissions: perm_opts
      };
      _results = [];
      for (plugin in plugins) {
        opts = plugins[plugin];
        _results.push(annotator.annotator('addPlugin', plugin, opts));
      }
      return _results;
    }
  };

}).call(this);
