<?php

/**
 * Implements hook_menu().
 */
function comparison_plugin_menu() {
  $items['comparison/reference'] = array(
    'title' => '',
    'page callback' => 'comparison_plugin_default',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );

  $items['comparison/reference/%'] = array(
    'title callback' => 'comparison_plugin_page_title_callback',
    'title arguments' => array(2),
    'page callback' => 'comparison_plugin_list',
    'page arguments' => array(2),
    'access callback' => 'og_is_member',
    'access arguments' => array('node', 2),
  );

  return $items;
}

function comparison_plugin_page_title_callback($nid) {
  $group = node_load($nid);

  return $group->title . ' Comparisons';
}

/**
 * Implements hook_views_api().
 */
function comparison_plugin_views_api() {
  return array(
    "api" => "3.0",
    "template path" => drupal_get_path("module", "comparison_plugin") . "/templates",
  );
}

function comparison_plugin_list($nid) {
  drupal_add_js(drupal_get_path('module', 'comparison_plugin') . '/plugins/comparison_reference/js/comparison_reference_popup.js');
  drupal_add_css(drupal_get_path('module', 'comparison_plugin') . '/plugins/comparison_reference/comparison_reference.css');

  $comparison_images = views_embed_view('comparisons', 'block_list', $nid);
  return $comparison_images;
}

function comparison_plugin_default() {
  drupal_add_css(drupal_get_path('module', 'comparison_plugin') . '/plugins/comparison_reference/comparison_reference.css');

  $comparison_images = views_embed_view('comparisons', 'block_list');
  return $comparison_images;
}

function comparison_plugin_wysiwyg_include_directory($type) {
  return $type;
}

/**
 * Implements hook_views_default_views().
 */
function comparison_plugin_views_default_views() {
  $export = array();
  
  $view = new view();
  $view->name = 'comparison_reference_list';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'file_managed';
  $view->human_name = 'Comparison Reference List';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Comparison Reference List';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'list';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = '<div>There are no comparison images for this content.</div>
  <br />
  <div><a href="#" onclick="window.close();">close window</a></div>';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  /* Relationship: Entity Reference: Referencing entity */
  $handler->display->display_options['relationships']['reverse_field_image_references_node']['id'] = 'reverse_field_image_references_node';
  $handler->display->display_options['relationships']['reverse_field_image_references_node']['table'] = 'file_managed';
  $handler->display->display_options['relationships']['reverse_field_image_references_node']['field'] = 'reverse_field_image_references_node';
  $handler->display->display_options['relationships']['reverse_field_image_references_node']['required'] = TRUE;
  /* Field: File: File ID */
  $handler->display->display_options['fields']['fid']['id'] = 'fid';
  $handler->display->display_options['fields']['fid']['table'] = 'file_managed';
  $handler->display->display_options['fields']['fid']['field'] = 'fid';
  $handler->display->display_options['fields']['fid']['label'] = '';
  $handler->display->display_options['fields']['fid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['fid']['element_label_colon'] = FALSE;
  /* Field: File: Name */
  $handler->display->display_options['fields']['filename']['id'] = 'filename';
  $handler->display->display_options['fields']['filename']['table'] = 'file_managed';
  $handler->display->display_options['fields']['filename']['field'] = 'filename';
  $handler->display->display_options['fields']['filename']['label'] = '';
  $handler->display->display_options['fields']['filename']['exclude'] = TRUE;
  $handler->display->display_options['fields']['filename']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['filename']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['filename']['element_label_colon'] = FALSE;
  /* Field: File: Path */
  $handler->display->display_options['fields']['uri']['id'] = 'uri';
  $handler->display->display_options['fields']['uri']['table'] = 'file_managed';
  $handler->display->display_options['fields']['uri']['field'] = 'uri';
  $handler->display->display_options['fields']['uri']['label'] = '';
  $handler->display->display_options['fields']['uri']['exclude'] = TRUE;
  $handler->display->display_options['fields']['uri']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['uri']['file_download_path'] = TRUE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<a class="comparison-reference-link" href="#" uri="[uri]">[filename]</a>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  /* Contextual filter: Content: Nid */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'node';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['relationship'] = 'reverse_field_image_references_node';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'empty';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
  /* Filter criterion: File: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'file_managed';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'image' => 'image',
  );

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['path'] = 'comparison-reference-list';

  /* Display: Block */
  $handler = $view->new_display('block', 'Block', 'block_list');
  $export['comparison_reference_list'] = $view;

  return $export;
}